name: Release on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: |
        mkdir -p dist
        go build -o dist/gohush ./cmd/main.go

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/gohush
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
